### ISSUE TITLE
menu is open and stuck on mobile sizes

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-jpo-country#2]
![menu open](https://cloud.githubusercontent.com/assets/19909772/17975554/746d462c-6aea-11e6-86d6-a498f65eb0a3.PNG)

Actually I think the issue regards all the templates, but it's difficult to review them with most of the screen hidden :/

**Comment by matthewmorek** [comment]
@jrah Could you please check out what the issue is and fix it for all repos? It looks like the bindings for the menu are not being processed correctly via JavaScript.

Try to follow up using examples from [WFP UI Docs](http://cdn.wfp.org/guides/ui/v0.11.0/components/header/). The `v0.12.1` implementation seem to be broken, maybe it's an issue with `wfp/ui`?

**Comment by andrewholgate** [comment]
@jrah In the meantime, can you please just hide this pop-up menu as it is blocking us from reviewing all of the templates.

**Comment by jrah** [comment]
@andrewholgate 

I will push a commit now.
